Wed Jan 23 21:23:42 IST 2013 Thread[main,5,main] Cleanup action starting
ERROR XBM0J: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at liquibase.integration.servlet.LiquibaseServletListener.contextInitialized(LiquibaseServletListener.java:125)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:644)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:229)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1158)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:587)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:436)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at com.nvarghese.funtoo.FuntooServer.startServer(FuntooServer.java:95)
	at com.nvarghese.funtoo.FuntooServer.main(FuntooServer.java:162)
Cleanup action completed
Wed Jan 23 21:23:42 IST 2013 Thread[main,5,main] Cleanup action starting
java.sql.SQLException: Failed to create database 'funtooDB', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at liquibase.integration.servlet.LiquibaseServletListener.contextInitialized(LiquibaseServletListener.java:125)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:644)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:229)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1158)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:587)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:436)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at com.nvarghese.funtoo.FuntooServer.startServer(FuntooServer.java:95)
	at com.nvarghese.funtoo.FuntooServer.main(FuntooServer.java:162)
Caused by: java.sql.SQLException: Failed to create database 'funtooDB', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 23 more
Caused by: java.sql.SQLException: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	... 20 more
Caused by: ERROR XBM0J: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
	... 20 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at liquibase.integration.servlet.LiquibaseServletListener.contextInitialized(LiquibaseServletListener.java:125)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:644)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:229)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1158)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:587)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:436)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at com.nvarghese.funtoo.FuntooServer.startServer(FuntooServer.java:95)
	at com.nvarghese.funtoo.FuntooServer.main(FuntooServer.java:162)
Caused by: java.sql.SQLException: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 25 more
Caused by: ERROR XBM0J: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
	... 20 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
java.sql.SQLException: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at liquibase.integration.servlet.LiquibaseServletListener.contextInitialized(LiquibaseServletListener.java:125)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:644)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:229)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1158)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:587)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:436)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at com.nvarghese.funtoo.FuntooServer.startServer(FuntooServer.java:95)
	at com.nvarghese.funtoo.FuntooServer.main(FuntooServer.java:162)
Caused by: ERROR XBM0J: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
	... 20 more
============= end nested exception, level (2) ===========
============= begin nested exception, level (3) ===========
ERROR XBM0J: Directory /mnt/data1/workspaces/jboss7TutsWx/Funtoo/funtooDB already exists.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$9.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.createServiceRoot(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	at org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
	at org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDataSource.getConnection(Unknown Source)
	at liquibase.integration.servlet.LiquibaseServletListener.contextInitialized(LiquibaseServletListener.java:125)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:644)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:229)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1158)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:587)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:436)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:253)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:58)
	at com.nvarghese.funtoo.FuntooServer.startServer(FuntooServer.java:95)
	at com.nvarghese.funtoo.FuntooServer.main(FuntooServer.java:162)
============= end nested exception, level (3) ===========
Cleanup action completed
